FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml .
COPY backend/ ./backend/
COPY alembic.ini .
COPY db/ ./db/
COPY start.sh .

RUN uv pip install --system -e ".[dev]" && chmod +x start.sh

CMD ["./start.sh"]
